# CaelusOS Welcome Module Config
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

requirements:
    requiredStorage: 15
    requiredRAM: 2.0
    internetCheckUrl: http://deb.debian.org
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
