#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --architectures amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-packages "linux-image" \
    --apt-indices false \
    --apt-options "--yes -o Acquire::Check-Valid-Until=false -o Acquire::Retries=10 -o Acquire::http::Timeout=30" \
    --cache true \
    --cache-packages true \
    --checksums sha256 \
    --compression squashfs \
    --chroot-filesystem squashfs \
    --binary-images iso-hybrid \
    --bootloader syslinux \
    --memtest none \
    --security false \
    --debian-installer false \
    --iso-application "CaelusOS Live GNU/Linux" \
    --iso-preparer "CaelusOS Team <https://caelusos.org>" \
    --iso-publisher "CaelusOS Project" \
    --iso-volume "CAELUS_OS_LIVE" \
    "${@}"
