#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --architectures amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --apt-options "--yes" \
    --checksums sha256 \
    --compression squashfs \
    --chroot-filesystem squashfs \
    --binary-images iso-hybrid \
    --bootloader grub-efi \
    --security false \
    --debian-installer false \
    --iso-application "CaelusOS Live GNU/Linux" \
    --iso-preparer "CaelusOS Team <https://caelusos.org>" \
    --iso-publisher "CaelusOS Project" \
    --iso-volume "CAELUS_OS_LIVE" \
    "${@}"
